#!/bin/bash

CASTLE_NAME="homeshick-base"
GITFLOW_URL="https://raw.github.com/nvie/gitflow/develop/contrib/gitflow-installer.sh"

if [ -f /etc/debian_version ]
then
  if ! hash sudo 2> /dev/null
  then
    echo "Please install sudo!"
    exit 1
  fi

  installed=$(sudo dpkg -l bash-completion > /dev/null 2>&1)
  if [ $? -eq 1 ]
  then
    sudo apt-get install bash bash-completion 
  fi

  installed=$(sudo dpkg -l git-core > /dev/null 2>&1)
  if [ $? -eq 1 ]
  then
    sudo apt-get install git-core
  fi

  if ! hash git-flow 2> /dev/null
  then
    curl ${GITFLOW_URL} | sudo bash
  fi
fi

if [ -f /etc/SuSE-release ]
then
  if ! hash sudo 2> /dev/null
  then
    echo "Please install sudo!"
    exit 1
  fi

  installed=$(zypper se -i bash-completion > /dev/null 2>&1)
  if [ $? -ne 0 ]
  then
    sudo zypper install bash bash-completion 
  fi

  installed=$(zypper se -i git > /dev/null 2>&1)
  if [ $? -ne 0 ]
  then
    sudo zypper install git
  fi

  if ! hash git-flow 2> /dev/null
  then
    curl ${GITFLOW_URL} | sudo bash
  fi
fi

if [ -f /usr/bin/sw_vers ]
then
  if ! hash brew 2> /dev/null
  then
    echo "Please install homebrew!"
    exit 1
  fi

  installed=$(brew list bash-completion > /dev/null 2>&1)
  if [ $? -eq 1 ]
  then
    brew install bash bash-completion 
  fi

  installed=$(brew list git > /dev/null 2>&1)
  if [ $? -eq 1 ]
  then
    brew install git 
  fi

  if ! hash git-flow 2> /dev/null
  then
    curl ${GITFLOW_URL} | sudo bash
  fi
fi

if [ ! -d ~/.homesick/repos/homeshick ]
then
  git clone https://github.com/andsens/homeshick.git ~/.homesick/repos/homeshick
fi

source ~/.homesick/repos/homeshick/homeshick.sh

if [ -d ~/.homesick/repos/${CASTLE_NAME} ]
then
  homeshick pull -f ${CASTLE_NAME}
else
  homeshick clone -f https://github.com/tboerger/${CASTLE_NAME}
fi

homeshick link -f ${CASTLE_NAME}
