#!/usr/bin/env ruby
# Taken from https://github.com/mislav/dotfiles/blob/master/bin/each-git

dirs = Dir['**/.git'].map do |git|
  File.dirname(git)
end

def prompt
  print ">> "
  gets
end

puts "Press Ctrl+D to break out of the loop"
while command = prompt
  dirs.each do |dir|
    begin
      Dir.chdir(dir) do
        puts "~ #{dir}:"
        system command
      end
    rescue Errno::ENOENT => e
      $stderr.puts e.message
    end
  end
end
