#!/usr/bin/env bash
# Usage: git autofixup
#
# Commits the staged change as a fixup for the last commit that touched the
# changed line. Useful for preparing for a `git rebase --autosquash`.

# Taken from https://github.com/mislav/dotfiles/blob/master/bin/git-autofixup

set -e

[ "$1" = "-h" ] && exec sed -ne '/^#/!q;s/.\{1,2\}//;1d;p' < "$0"

git diff --no-prefix --cached -U0 | awk '
  /^--- / { print $2 }
  /^@@ /  { print $2 * -1; exit }
' | xargs | {
  read filename lineno
  sha="$(git blame HEAD "${filename}" -L "${lineno},+1" | awk '{ print $1 }')"

  git commit --fixup "${sha}"
}
